### PR TITLE
Fix error while iterating over unread news while receiving confirmation

### LINKED ISSUE #375: Failed to save news action
```java
Non-fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
       at java.util.HashMap$KeyIterator.next(HashMap.java:885)
       at com.mobicage.rogerthat.plugins.news.NewsChannel.saveCallInDB(NewsChannel.java:536)
       at com.mobicage.rogerthat.plugins.news.NewsChannel.addCallToDB(NewsChannel.java:498)
       at com.mobicage.rogerthat.plugins.news.NewsChannel.readNews(NewsChannel.java:465)
       at com.mobicage.rogerthat.plugins.news.NewsPlugin$4.safeRun(NewsPlugin.java:443)
       at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

### PR DESCRIPTION
**Pull request by lucasvanhalst**
Closes #375

### CODE REVIEW

File: rogerthat/src/main/java/com/mobicage/rogerthat/plugins/news/NewsChannel.java [hunk 1]
```diff
@@ -569,11 +569,15 @@ private void loadCallsFromDB() {
     }
 
     private void resendUnsentItems() {
-        for (Long newsId : mReadsToSend) {
+        // Take a copy of the values to avoid ConcurrentModificationException
+        // This would happen hen we receive a confirmation of one of the commands while iterating over the values.
+        final Long[] readIds = mReadsToSend.toArray(new Long[mReadsToSend.size()]);
+        final Long[] rogerIds = mReadsToSend.toArray(new Long[mRogersToSend.size()]);
```
Comment (bart-at-mobicage) [inline rogerthat/src/main/java/com/mobicage/rogerthat/plugins/news/NewsChannel.java]: should be `mRogersToSend.toArray`

**Comment by RubenMattan** [comment]
Can u validate if that array isn't changed on multiple threads?
