### PR TITLE
Fix a few errors which caused news count badges to not be updated

### LINKED ISSUE #382: There's no badge number on custom feeds
We posted 3 news items in a custom feed. However, none of the apps showed a badge number in the sidebar menu.

### PR DESCRIPTION
**Pull request by lucasvanhalst**
Closes #382

### CODE REVIEW

File: rogerthat/src/main/java/com/mobicage/rogerthat/plugins/news/NewsPlugin.java [hunk 1]
```diff
@@ -526,7 +525,8 @@ public void increaseBadgeCount(String feedName) {
         }
 
         if (currentActivity instanceof NewsActivity) {
-            if (((NewsActivity) currentActivity).getFeedName() == feedName) {
```
Comment (lucasvanhalst) [inline rogerthat/src/main/java/com/mobicage/rogerthat/plugins/news/NewsPlugin.java]: this was only true in case both were `null`

File: rogerthat/src/main/java/com/mobicage/rogerthat/plugins/news/NewsPlugin.java [hunk 2]
```diff
@@ -312,19 +311,19 @@ private void filterOnBroadcastTypes(List<AppNewsInfoTO> newsItems) {
...
+        for (int i = 0; i < items.size(); i++) {
+            ids[i] = items.get(i).id;
         }
         return ids;
     }
 
     private void sendGetNewsUpdates(String feedName, List<AppNewsInfoTO> newItems, List<AppNewsInfoTO> updatedItems) {
         Intent intent = new Intent(NewsPlugin.GET_NEWS_RECEIVED_INTENT);
         intent.putExtra("feed_name", feedName);
-        intent.putExtra("new_ids", getItemIds(newItems).toArray());
```
Comment (lucasvanhalst) [inline rogerthat/src/main/java/com/mobicage/rogerthat/plugins/news/NewsPlugin.java]: this was giving a `ClassCastException` for me (expected long[], got Object[])
